"""razorpay correlation columns

Revision ID: 0da9a94663e8
Revises: 213fa89dbc2b
Create Date: 2026-06-02 22:49:24.880389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da9a94663e8'
down_revision: Union[str, Sequence[str], None] = '213fa89dbc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('provider_plan_id', sa.String(length=64), nullable=True))
    op.add_column('subscriptions', sa.Column('checkout_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'checkout_url')
    op.drop_column('plans', 'provider_plan_id')
    # ### end Alembic commands ###
