"""watch_progress hidden_from_continue + storage TTL field

Revision ID: 117d9ec02783
Revises: 67d9bd376b6d
Create Date: 2026-06-03 12:48:23.790807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117d9ec02783'
down_revision: Union[str, Sequence[str], None] = '67d9bd376b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch_progress', sa.Column('hidden_from_continue', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch_progress', 'hidden_from_continue')
    # ### end Alembic commands ###
