"""subtitle storage_url + episode_id + label

Revision ID: 7666a2b6bf89
Revises: a145b5878354
Create Date: 2026-06-03 22:53:27.492398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7666a2b6bf89'
down_revision: Union[str, Sequence[str], None] = 'a145b5878354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_tracks', sa.Column('episode_id', sa.Integer(), nullable=True))
    op.add_column('subtitle_tracks', sa.Column('storage_url', sa.String(length=1024), nullable=True))
    op.add_column('subtitle_tracks', sa.Column('label', sa.String(length=64), nullable=True))
    op.alter_column('subtitle_tracks', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_subtitle_tracks_episode_id'), 'subtitle_tracks', ['episode_id'], unique=False)
    op.create_foreign_key(op.f('fk_subtitle_tracks_episode_id_episodes'), 'subtitle_tracks', 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_subtitle_tracks_episode_id_episodes'), 'subtitle_tracks', type_='foreignkey')
    op.drop_index(op.f('ix_subtitle_tracks_episode_id'), table_name='subtitle_tracks')
    op.alter_column('subtitle_tracks', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subtitle_tracks', 'label')
    op.drop_column('subtitle_tracks', 'storage_url')
    op.drop_column('subtitle_tracks', 'episode_id')
    # ### end Alembic commands ###
