"""is_free flag on Title + Episode

Revision ID: c599e9fb1787
Revises: 117d9ec02783
Create Date: 2026-06-03 13:19:37.428857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c599e9fb1787'
down_revision: Union[str, Sequence[str], None] = '117d9ec02783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. Adds is_free with server_default='false' so existing
    rows backfill cleanly; the default is then dropped so future inserts
    must specify a value (model has default=False)."""
    op.add_column(
        'episodes',
        sa.Column('is_free', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'titles',
        sa.Column('is_free', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # Drop the server defaults; existing rows now have values, future inserts
    # come from the SQLAlchemy model's default=False.
    op.alter_column('episodes', 'is_free', server_default=None)
    op.alter_column('titles', 'is_free', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titles', 'is_free')
    op.drop_column('episodes', 'is_free')
    # ### end Alembic commands ###
